import { request } from "@playwright/test";

const RESIDENT_EMAIL = "testresident@gmail.com";
const ADMIN_EMAIL = "admin@cityconnect.com";

export type ServiceRequestRecord = {
  id: string;
  title: string | null;
  description: string | null;
  status: string;
  createdAt: string;
  estateId?: string | null;
};

function resolveBaseURL(baseURL?: string) {
  return baseURL || "http://localhost:5000";
}

/**
 * Creates a real service request through the current resident API.
 */
export async function ensureSampleRequest(baseURL?: string): Promise<ServiceRequestRecord> {
  const context = await request.newContext({ baseURL: resolveBaseURL(baseURL) });
  try {
    const estatesResponse = await context.get("/api/my-estates", {
      headers: { "x-user-email": RESIDENT_EMAIL },
    });
    if (!estatesResponse.ok()) {
      throw new Error(`Failed to load resident estates (${estatesResponse.status()})`);
    }

    const estates = (await estatesResponse.json()) as Array<{ id?: string | null }>;
    const estateId = String(estates.find((estate) => estate?.id)?.id || "").trim();
    if (!estateId) {
      throw new Error("Resident has no estate available for request test data.");
    }

    const response = await context.post("/api/service-requests", {
      headers: { "x-user-email": RESIDENT_EMAIL, "Content-Type": "application/json" },
      data: {
        estateId,
        category: "general_repairs",
        description: `E2E sample service request ${Date.now()}`,
        budget: "150000",
        urgency: "medium",
        location: "Victoria Garden City, Lagos",
        specialInstructions: "Generated by service request E2E helper",
      },
    });

    if (!response.ok()) {
      throw new Error(`Failed to create sample request (${response.status()}): ${await response.text()}`);
    }

    const record = (await response.json()) as ServiceRequestRecord;
    return {
      ...record,
      status: String(record.status || "PENDING").toUpperCase(),
      title: record.title ?? "General Repairs",
      estateId,
    };
  } finally {
    await context.dispose();
  }
}

/**
 * Forces a known status on a request so tests can be deterministic.
 */
export async function setRequestStatus(
  id: string,
  status: string,
  baseURL?: string
): Promise<ServiceRequestRecord> {
  const context = await request.newContext({ baseURL: resolveBaseURL(baseURL) });
  try {
    const response = await context.patch(`/api/requests/${id}/status`, {
      headers: { "x-user-email": ADMIN_EMAIL, "Content-Type": "application/json" },
      data: { status },
    });

    if (!response.ok()) {
      const body = await response.text();
      throw new Error(`Failed to update status (${response.status()}): ${body}`);
    }

    return (await response.json()) as ServiceRequestRecord;
  } finally {
    await context.dispose();
  }
}

/**
 * Ensures we have a request in the PENDING state by resetting the sample.
 */
export async function ensurePendingRequest(baseURL?: string): Promise<ServiceRequestRecord> {
  const sample = await ensureSampleRequest(baseURL);
  if (sample.status === "PENDING") {
    return sample;
  }
  return setRequestStatus(sample.id, "PENDING", baseURL);
}
