export type MarketplaceCategoryPreset = {
  name: string;
  emoji: string;
  description: string;
};

export const MARKETPLACE_CATEGORY_PRESETS: MarketplaceCategoryPreset[] = [
  { emoji: "🍎", name: "Fresh Fruits", description: "Apples, pears, and orchard picks." },
  { emoji: "🍍", name: "Tropical Fruits", description: "Bananas, pineapples, and sunny flavors." },
  { emoji: "🍓", name: "Berry Basket", description: "Strawberries, blueberries, and berry mixes." },
  { emoji: "🥑", name: "Avocados & Healthy Fats", description: "Avocados, olives, and wholesome fats." },
  { emoji: "🥬", name: "Leafy Greens", description: "Spinach, kale, and salad-ready greens." },
  { emoji: "🥕", name: "Root Vegetables", description: "Carrots, beets, and hearty tubers." },
  { emoji: "🫑", name: "Crunchy Peppers", description: "Bell peppers, chilies, and spice." },
  { emoji: "🥒", name: "Cool Cucumbers", description: "Cucumbers, zucchinis, and refreshing gourds." },
  { emoji: "🍅", name: "Tomato Patch", description: "Tomatoes of every shape for cooking and salads." },
  { emoji: "🧄", name: "Aromatic Bulbs", description: "Garlic, shallots, and kitchen aromatics." },
  { emoji: "🍄", name: "Mushrooms & Fungi", description: "Button, oyster, shiitake, and wild picks." },
  { emoji: "🌶️", name: "Hot & Spicy", description: "Peppers, chilies, and fiery sauces." },
  { emoji: "🫘", name: "Beans & Pulses", description: "Protein-rich beans, peas, and lentils." },
  { emoji: "🍚", name: "Whole Grains", description: "Rice, millet, quinoa, and pantry grains." },
  { emoji: "🥨", name: "Artisan Bread", description: "Sourdoughs, pretzels, and bakery loaves." },
  { emoji: "🥐", name: "Pastries & Croissants", description: "Flaky croissants, danishes, and baked treats." },
  { emoji: "🥯", name: "Bagels & Rolls", description: "Bagels, buns, and sandwich-ready rolls." },
  { emoji: "🧁", name: "Cupcakes & Treats", description: "Cupcakes, muffins, and sweet bites." },
  { emoji: "🧇", name: "Breakfast Pantry", description: "Pancake mixes, waffles, and cereals." },
  { emoji: "🥖", name: "Baguettes & Loaves", description: "French loaves, ciabatta, and crusty bread." },
  { emoji: "🥩", name: "Premium Steaks", description: "Steaks, roasts, and butcher-cut beef." },
  { emoji: "🍗", name: "Poultry Counter", description: "Chicken, turkey, and seasoned poultry cuts." },
  { emoji: "🥓", name: "Cured & Smoked", description: "Bacon, prosciutto, and smoked meats." },
  { emoji: "🍖", name: "BBQ Favorites", description: "Ribs, marinades, and grill-ready meats." },
  { emoji: "🐟", name: "Fresh Seafood", description: "Fish fillets, salmon, and ocean catch." },
  { emoji: "🦐", name: "Shellfish Market", description: "Shrimp, prawns, and shellfish delicacies." },
  { emoji: "🍣", name: "Sushi Essentials", description: "Sushi rice, nori, and sashimi-grade picks." },
  { emoji: "🥚", name: "Eggs & Dairy", description: "Farm eggs, yogurt, and cultured dairy." },
  { emoji: "🧀", name: "Cheese Cellar", description: "Cheddar, brie, and gourmet cheeses." },
  { emoji: "🥛", name: "Milk & Cream", description: "Fresh milk, creamers, and plant-based milks." },
  { emoji: "🧈", name: "Butter & Spreads", description: "Butter, ghee, nut spreads, and jams." },
  { emoji: "🥫", name: "Pantry Staples", description: "Canned goods, stocks, and shelf-ready basics." },
  { emoji: "🍝", name: "Pasta & Sauces", description: "Dried pasta, pesto, and tomato sauces." },
  { emoji: "🍜", name: "Noodle Bowls", description: "Instant noodles, ramen, and pho kits." },
  { emoji: "🥟", name: "Dumplings & Dim Sum", description: "Frozen dumplings, buns, and dim sum bites." },
  { emoji: "🌯", name: "Wraps & Burritos", description: "Wraps, tortillas, and burrito fillings." },
  { emoji: "🥪", name: "Sandwich Fixings", description: "Cold cuts, deli meats, and sandwich spreads." },
  { emoji: "🍕", name: "Pizza Night", description: "Pizza bases, sauces, and cheesy toppings." },
  { emoji: "🍔", name: "Burgers & Sliders", description: "Burger patties, buns, and slider kits." },
  { emoji: "🌭", name: "Hotdogs & Sausages", description: "Hotdogs, sausages, and grilling condiments." },
  { emoji: "🌮", name: "Taco Tuesday", description: "Taco shells, fillings, and fiesta toppings." },
  { emoji: "🥗", name: "Ready Salads", description: "Prepped salads, dressings, and crunchy add-ons." },
  { emoji: "🍱", name: "Bento & Meal Prep", description: "Meal boxes, sides, and ready-to-go combos." },
  { emoji: "🍲", name: "Soups & Stews", description: "Broths, hearty soups, and stew starters." },
  { emoji: "🍛", name: "Curry Corner", description: "Curries, spice pastes, and simmer sauces." },
  { emoji: "🍩", name: "Donuts & Cakes", description: "Donuts, cakes, and bakery desserts." },
  { emoji: "🍪", name: "Cookie Jar", description: "Cookies, biscuits, and dunk-worthy treats." },
  { emoji: "🍫", name: "Chocolate Shop", description: "Chocolate bars, truffles, and cocoa gifts." },
  { emoji: "🍿", name: "Movie Snacks", description: "Popcorn, chips, and crunchy nibbles." },
  { emoji: "🍨", name: "Frozen Desserts", description: "Ice cream, gelato, and frozen sweets." },
  { emoji: "🍯", name: "Honey & Sweet Spreads", description: "Honey, syrups, and breakfast spreads." },
  { emoji: "☕", name: "Coffee & Tea", description: "Beans, loose-leaf tea, and brewing gear." },
  { emoji: "🧋", name: "Bubble Tea & Smoothies", description: "Boba kits, smoothie mixes, and shakers." },
  { emoji: "🥤", name: "Soft Drinks", description: "Sodas, flavored waters, and sparkling cans." },
  { emoji: "🧃", name: "Juice Bar", description: "Cold-pressed juices and fruity blends." },
  { emoji: "🍺", name: "Craft Beers", description: "Lagers, ales, and local craft brews." },
  { emoji: "🍷", name: "Wine Cellar", description: "Red, white, and sparkling wines." },
  { emoji: "🍼", name: "Baby Care", description: "Formula, baby food, and infant essentials." },
  { emoji: "🧸", name: "Kids' Corner", description: "Toys, storybooks, and playful extras." },
  { emoji: "🐾", name: "Pet Pantry", description: "Pet food, treats, and grooming care." },
  { emoji: "💄", name: "Personal Care", description: "Skincare, lotions, and grooming kits." },
  { emoji: "🧼", name: "Bath Essentials", description: "Bath soaps, body wash, and spa items." },
  { emoji: "🪥", name: "Oral Care", description: "Toothbrushes, toothpaste, and mouthwash." },
  { emoji: "🧽", name: "Cleaning Sponges", description: "Sponges, scrubbers, and cleaning pads." },
  { emoji: "🧹", name: "Brooms & Tools", description: "Brooms, mops, and household tools." },
  { emoji: "🧺", name: "Laundry Care", description: "Detergents, softeners, and hampers." },
  { emoji: "🧻", name: "Paper Goods", description: "Tissues, paper towels, and napkins." },
  { emoji: "🪣", name: "Buckets & Utility", description: "Buckets, basins, and cleaning helpers." },
  { emoji: "🧊", name: "Ice & Cold Packs", description: "Ice trays, gel packs, and chillers." },
  { emoji: "🍽️", name: "Tableware", description: "Plates, cutlery, and serving essentials." },
  { emoji: "🔪", name: "Kitchen Tools", description: "Knives, utensils, and prep gadgets." },
  { emoji: "🍳", name: "Cookware", description: "Pans, pots, and stovetop heroes." },
  { emoji: "🥣", name: "Mixing Bowls", description: "Bowls, measuring sets, and baking prep." },
  { emoji: "🌿", name: "Herbs & Seasoning", description: "Herbs, spice jars, salts, and flavor boosters." },
  { emoji: "🎂", name: "Celebration Cakes", description: "Party cakes, toppers, and dessert décor." },
  { emoji: "🎁", name: "Gifts & Wraps", description: "Gift bags, wraps, and curated presents." },
  { emoji: "📚", name: "Books & Stationery", description: "Books, planners, and study supplies." },
  { emoji: "🗂️", name: "Desk Supplies", description: "Pens, notebooks, and office must-haves." },
  { emoji: "💡", name: "Lighting & Decor", description: "Lamps, bulbs, and ambient decor." },
  { emoji: "🛋️", name: "Furniture & Seating", description: "Chairs, stools, and cozy seating." },
  { emoji: "🛏️", name: "Bedroom Comforts", description: "Bedsheets, duvets, and pillows." },
  { emoji: "👕", name: "Casual Apparel", description: "Tees, polos, and everyday wear." },
  { emoji: "👗", name: "Dresses & Occasion", description: "Dresses, gowns, and event styles." },
  { emoji: "👖", name: "Denim Picks", description: "Jeans, jeggings, and denim staples." },
  { emoji: "👟", name: "Sneakers & Trainers", description: "Sporty and casual footwear." },
  { emoji: "👠", name: "Formal Footwear", description: "Heels, loafers, and office shoes." },
  { emoji: "👜", name: "Bags & Purses", description: "Handbags, totes, and statement purses." },
  { emoji: "💍", name: "Jewelry Counter", description: "Rings, necklaces, and keepsakes." },
  { emoji: "⌚", name: "Watches & Wearables", description: "Smartwatches and timeless wristwear." },
  { emoji: "📱", name: "Mobile Accessories", description: "Cases, chargers, and mobile add-ons." },
  { emoji: "💻", name: "Tech & Gadgets", description: "Laptops, tablets, and smart devices." },
  { emoji: "🎧", name: "Audio Gear", description: "Headphones, speakers, and sound gear." },
  { emoji: "🖥️", name: "Monitors & Displays", description: "Monitors, mounts, and display hubs." },
  { emoji: "📺", name: "Home Entertainment", description: "Smart TVs, remotes, and streaming gear." },
  { emoji: "🎮", name: "Gaming Lounge", description: "Consoles, controllers, and accessories." },
  { emoji: "⚽", name: "Sports Gear", description: "Balls, fitness accessories, and training kits." },
  { emoji: "🛒", name: "Shopping Essentials", description: "Reusable bags, totes, and cart helpers." },
];
